name: "Update flake.lock (root)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 0"

jobs:
  update:
    uses: ./.github/workflows/reusable/update-flakelock.yaml
    with:
      flake-path: "."
