name: "Update flake.lock (root)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 0"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/update-flakelock.yaml
    with:
      flake-path: "."
