name: "Update flake.lock (nixos)"

on:
  workflow_dispatch:

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/update-flakelock
        with:
          variant: nixos
          inputs-to-update: "nixpkgs home-manager sops-nix ponytail"
