name: "Update flake.lock (full)"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 3"  # Wednesdays at 04:00 UTC

jobs:
  update-flake-lock:
    uses: ./.github/workflows/update-flakelock-reusable.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      variant: full
