name: "Update flake.lock (nixos)"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 3"  # Wednesdays at 04:00 UTC

jobs:
  update-flake-lock:
    uses: ./.github/workflows/update-flakelock-reusable.yaml
    with:
      inputs-to-update: "nixpkgs home-manager sops-nix ponytail"
      branch: "update-flake-lock-nixos"
      pr-title: "Update flake.lock (nixos)"
