name: "Update flake.lock (full)"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 2"  # Tuesdays at 07:00 UTC, shortly after upstream nixpkgs-weekly release (~05:00 UTC)

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/update-flakelock
        with:
          variant: full
